baseURL = 'https://konyrtai.com/'
languageCode = 'en-us'
title = 'Alibek Konyrtai - Software Developer'
theme = 'PaperMod'

[params]
  env = 'production'
  title = 'Alibek Konyrtai'
  description = 'Software Developer sharing insights on programming, technology, and development'
  author = 'Alibek Konyrtai'
  keywords = [ "Software Development", "Programming", "Technology", "Web Development" ]

  # Theme configuration
  defaultTheme = "auto"
  disableThemeToggle = false
  displayMode = "full"
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = false
  search = true
  twemoji = true
  twoslashemoji = true
  showreadingtime = true
  showshare = true
  showpostnavigators = true
  showbreadcrumbs = true
  showcodecopybuttons = true
  showwordcount = true
  showrss = true

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 20

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 30

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 40

[params.homeInfoParams]
  Title = "Alibek Konyrtai"
  Content = "Software Developer passionate about creating innovative solutions and sharing knowledge through programming insights."

[params.editPost]
  URL = "https://github.com/konyrtai/blog/tree/main/content"
  Text = "Suggest Changes"
  appendFilePath = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'
