baseURL = "https://konyrtai.github.io/blog/"
title = "Alibek Konyrtai — Blog"
defaultContentLanguage = "en"
pagination.pagerSize = 10
enableRobotsTXT = true

# Taxonomies
[taxonomies]
  category = "categories"
  tag = "tags"

# Меню (header)
[menu]
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 10
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 20
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 30
  [[menu.main]]
    name = "About me"
    url = "/about/"
    weight = 40

# PaperMod params
[params]
  env = "production"
  description = "Software Developer"
  author = "Alibek Konyrtai"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadcrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = false
  HideFooter = true

# Импорт PaperMod как модуля
[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"
