baseURL = "https://www.konyrtai.com/"
title = "Alibek Konyrtai — Blog"
languageCode = "en"
defaultContentLanguage = "en"
canonifyURLs = true
pagination.pagerSize = 10
enableRobotsTXT = true

[taxonomies]
  category = "categories"
  tag = "tags"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 10
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 20
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 30
  [[menu.main]]
    name = "About me"
    url = "/about/"
    weight = 40

[params]
  env = "production"
  description = "Software Developer"
  author = "Alibek Konyrtai"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadcrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = false
  HideFooter = true

[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"
